### ISSUE TITLE
client is crashing on sample app 

### ISSUE THREAD

**Issue by peererror** [ASMlover/study#1]

**Comment by ASMlover** [comment]
which sample? need more details

**Comment by peererror** [comment]
KcpNet-master client is crashing sorry for missing the details . I have compiled the library with latest dependencies .when I start kcpNet sample as server mode this worked and start to listen but when I start client from command line it crashes in boost io_Service run call .

**Comment by ASMlover** [comment]
Yes, the client is crashing for windows version building with debug mode.
Please try again.
If there's any another bugs, please tell me. Thanks

**Comment by peererror** [comment]
I want to ask is Ikcp is better than tcp or udp as I see you have experience with it I am trying to create a streaming server will it worth to try what do you say ? ..

**Comment by ASMlover** [comment]
More docs about [kcp](https://github.com/skywind3000/kcp), please click [kcp-doc](https://github.com/skywind3000/kcp/blob/master/README.en.md).
In my work field(FPS online, MMOARPG, MOBA), UDP brings better gaming experience, so it's worth to try. Of course TCP can work well, if there's no enough resource, TCP is also a good choice.
